Add - remove task
Obote/todo-list pull request #2
Opened 2023-07-15 15:39 UTC by Obote

2023-07-20 11:15 UTC, LionRouge1 reviewed
Hi @Obote, 

![done](https://media.giphy.com/media/gnE4FFhtFoLKM/giphy.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has not a summary describing in more detail the changes introduced in the PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-21 09:57 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Obote , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media0.giphy.com/media/gfsQffBnuc6e096brx/giphy.gif"/> |

## Highlights

- [ ]... ✅ Green linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 09:57 UTC, joskalenda commented on src/index.html
> +          </div> -->
- [ ] If you think this piece of code is not relevant to the milestone, please make sure you remove it or uncomment it as it makes your code dirty and unprofessional, @Obote

2023-07-21 09:57 UTC, joskalenda commented on src/localstorage.js
> +  return items;
- [ ] I think you need to take a close look at this record, the first issue is, the user is able to insert empty todo and the second one is, that anytime the user refreshes the app, all the data is lost. please work on fixing it

![6](https://github.com/Obote/todo-list/assets/77843050/9dba3bee-0b8e-46a6-b179-1e60199eeb69)

2023-07-21 09:57 UTC, joskalenda commented on README.md
- [ ] Please make sure you update your readme with the correct MIT license as for now, the [link](https://github.com/Obote/todo-list/blob/add-remove-task/LICENSE) to it is broken

2023-07-21 22:12 UTC, sumairq approved these changes
### Hi @Obote , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 22:12 UTC, merged